[package]
name = "input_loop"
version = "0.1.2"
edition = "2024"
description = "A utility for getting typed input from stdin with validation"
homepage = "https://github.com/SalladShooter/input_loop"
repository = "https://github.com/yourusername/input_loop"
authors = ["SalladShooter"]
license = "MIT"
readme = "README.md"

[lib]
name = "input_loop"
path = "src/lib.rs"

[[bin]]
name = "input-loop"
path = "src/main.rs"